// Map Russian/UI categories to English Search Queries for better API results
export const CATEGORY_MAP: Record<string, string> = {
  // General
  'Все видео': '',
  'All': '',
  'Premium': 'premium',
  'Любительское': 'amateur',
  'POV': 'pov',
  'Зрелые': 'milf',
  'Студентки': 'teen',
  'Блондинки': 'blonde',
  'Азиатки': 'asian',
  'БДСМ': 'bdsm',
  'Массаж': 'massage',
  'Групповое': 'group_sex',
  'Romance': 'romantic',
  'Романтика': 'romantic',
  
  // Him
  'Для него': 'straight',
  'Хардкор': 'hardcore',
  'Минет': 'blowjob',
  'Анал': 'anal',
  'Большая грудь': 'big_tits',
  'Мамочки': 'milf',
  'Чулки': 'stockings',
  'Молодые (18+)': 'teen',
  'Окончание': 'cumshot',
  'VR': 'vr',

  // Her
  'Для неё': 'for_women',
  'Чувственное': 'sensual',
  'Сюжет': 'story',
  'Соло парень': 'solo_male',
  'Кунилингус': 'cunnilingus',
  'Эротика': 'erotica',
  'Замедленно': 'slow_motion',
  'Софткор': 'softcore',
  'Пары': 'couples',
  'Аудио': 'audio',

  // Couples
  'Для пар': 'couples',
  'Виртуальный секс': 'virtual_sex',
  'Свинг': 'swingers',
  'Тройничок': 'threesome',
  'Обучающее': 'educational',

  // Gay
  'Твинки': 'twink',
  'Папики': 'daddy',
  'Медведи': 'bear',
  'Качки': 'jock',
  'Без защиты': 'bareback',
  'Военные': 'military',
  'Студенты': 'gay_student',

  // Trans
  'Транс соло': 'trans_solo',
  'Активы': 'trans_top',
  'Пассивы': 'trans_bottom',
  'Ледибой': 'ladyboy',
  'Транссексуалы': 'shemale',
  'Женственные': 'passable',
  'Транс азиатки': 'trans_asian',
  'Транс латинки': 'trans_latin',

  // General / Additional
  'Тату': 'tattoo',
  'Рыжие': 'redhead',
  'Брюнетки': 'brunette',
  'Латинки': 'latina',
  'Эбони': 'ebony',
  'Косплей': 'cosplay',
  'Хентай': 'hentai',
  'Мастурбация': 'masturbation',
  'Кастинг': 'casting',
  'Общественное место': 'public',
  'Вебкамеры': 'webcam',
  'ASMR': 'asmr',
  'Фетиш': 'fetish',
  'Ножки': 'feet',
  'Учительница': 'teacher',
  'Медсестра': 'nurse',
  'Русское': 'russian',
  'Секс-игрушки': 'toys',
  'Гаппинг': 'gaping',
  'Сквирт': 'squirt',
  'Кремпай': 'creampie',
  'Глубокая глотка': 'deepthroat',
  'Лицо': 'facial',
  'Отчим': 'stepdad',
  'Падчерица': 'stepdaughter',
  'Лесбиянки': 'lesbian',
  'Геи': 'gay',

  // Him Specific
  'Двойное проникновение': 'double_penetration',
  'ЖМЖ': 'threesome_ffm',
  'МЖМ': 'threesome_mmf',
  'Грязные разговоры': 'dirty_talk',
  'Принуждение': 'forced',
  'Колледж': 'college',
  'В машине': 'car_sex',
  'Секретарша': 'secretary',
  'Босс': 'boss',
  'Служанка': 'maid',
  'Официантка': 'waitress',
  'Спортзал': 'gym',
  'Йога': 'yoga',
  'Бассейн': 'pool',
  'Душ': 'shower',
  'Кухня': 'kitchen',

  // Her Specific
  'Женский оргазм': 'female_orgasm',
  'Страстный секс': 'passionate_sex',
  'Красивое белье': 'lingerie',
  'Игрушки': 'toys',
  'Шибари': 'shibari',
  'Доминирование': 'femdom',
  'Подчинение': 'submissive',
  'Джентльмен': 'gentleman',
  'Внимательный любовник': 'caring',
  'Прелюдия': 'foreplay',
  'Ласки': 'caress',
  'Поцелуи': 'kissing',
  'Объятия': 'cuddling',
  'Взгляд': 'eye_contact',
  'Атмосфера': 'romantic_atmosphere',
  'Свечи': 'candles',

  // Couples
  'Реальные пары': 'amateur_couple',
  'Домашнее': 'homemade',
  'Первый раз': 'first_time',
  'Эксперименты': 'experimental',
  'Тантра': 'tantra',
  'Камасутра': 'kamasutra',
  'Ролевые игры': 'roleplay',
  'Обмен партнерами': 'swingers',

  // Gay
  'Униформа': 'uniform',
  'Спорт': 'sport',
  'Раздевалка': 'locker_room',
  'Общежитие': 'dorm',
  'Друзья': 'friends',
  'Братья': 'brothers',
  'Отцы': 'daddies',
  'Сыновья': 'sons',
  'Латино': 'latino',
  'Азиаты': 'asian_gay',
  'Черные': 'black_gay',

  // Trans
  'Бисексуалы': 'bisexual',
  'Шимейл': 'shemale',
  'Т-Герл': 't-girl',
  'Кроссдрессер': 'crossdresser',
  'Сисси': 'sissy',
  'Феминизация': 'feminization',
  'Транс с парнем': 'trans_male',
  'Транс с девушкой': 'trans_female',

  // Lesbian
  'Подруги': 'friends',
  'Сестры': 'sisters',
  'Мама и дочь': 'mom_daughter',
  'Учитель и ученица': 'teacher_student',
  'Врач и пациент': 'doctor_patient',
  'Масло': 'oil',
  'Фистинг': 'fisting'
};
